var child = [
  { 'dupe': false, 'type': 4, 'name': 'session', 'dir': 'c0', 'linked': 2, 'url': 'http://107.20.213.223/auth/session/', 'fetched': true, 'code': 200, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0x1f8a7ca },
  { 'dupe': false, 'type': 8, 'name': 'Login', 'dir': 'c1', 'linked': 0, 'url': 'http://107.20.213.223/auth/Login', 'fetched': true, 'code': 200, 'len': 620, 'decl_mime': 'text/plain', 'sniff_mime': 'application/xhtml+xml', 'cset': 'windows-1250', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xbc1a8339 },
  { 'dupe': false, 'type': 8, 'name': 'style.css', 'dir': 'c2', 'linked': 2, 'url': 'http://107.20.213.223/auth/style.css', 'fetched': true, 'code': 200, 'len': 8411, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 8, 'name': 'xss', 'dir': 'c3', 'linked': 0, 'url': 'http://107.20.213.223/auth/xss', 'fetched': true, 'code': 200, 'len': 256, 'decl_mime': 'text/plain', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xd6bfd33e },
  { 'dupe': false, 'type': 16, 'name': 'control', 'dir': 'c4', 'linked': 0, 'url': 'http://107.20.213.223/auth/control', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'control.php', 'dir': 'c5', 'linked': 5, 'url': 'http://107.20.213.223/auth/control.php', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd559acab },
  { 'dupe': true, 'type': 16, 'name': 'index', 'dir': 'c6', 'linked': 0, 'url': 'http://107.20.213.223/auth/index', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff },
  { 'dupe': false, 'type': 16, 'name': 'login.php', 'dir': 'c8', 'linked': 2, 'url': 'http://107.20.213.223/auth/login.php', 'fetched': true, 'code': 200, 'len': 3057, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 1, 0, 0 ], 'sig': 0xffeddaa0 },
  { 'dupe': false, 'type': 16, 'name': 'logout', 'dir': 'c9', 'linked': 0, 'url': 'http://107.20.213.223/auth/logout', 'fetched': true, 'code': 302, 'len': 49, 'decl_mime': 'text/html', 'sniff_mime': 'text/plain', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 0, 0 ], 'sig': 0xd6a7d338 },
  { 'dupe': false, 'type': 16, 'name': 'xss.php', 'dir': 'c11', 'linked': 2, 'url': 'http://107.20.213.223/auth/xss.php', 'fetched': true, 'code': 302, 'len': 1131, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xffefffff }
];
