var child = [
  { 'dupe': false, 'type': 4, 'name': 'auth', 'dir': 'c0', 'linked': 5, 'url': 'http://107.20.213.223/auth/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 15, 'issue_cnt': [ 9, 0, 1, 0, 0 ], 'sig': 0x1c0312d2 },
  { 'dupe': false, 'type': 8, 'name': 'hello.php', 'dir': 'c1', 'linked': 5, 'url': 'http://107.20.213.223/hello.php', 'fetched': true, 'code': 200, 'len': 2849, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 17, 'issue_cnt': [ 0, 16, 16, 2, 0 ], 'sig': 0xc54fbcd0 },
  { 'dupe': false, 'type': 8, 'name': 'process.php', 'dir': 'c2', 'linked': 2, 'url': 'http://107.20.213.223/process.php', 'fetched': true, 'code': 200, 'len': 1380, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 0, 2, 1, 0, 0 ], 'sig': 0xfe0a313a },
  { 'dupe': false, 'type': 8, 'name': 'products.php', 'dir': 'c3', 'linked': 2, 'url': 'http://107.20.213.223/products.php', 'fetched': true, 'code': 200, 'len': 2934, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 3, 2, 0, 0 ], 'sig': 0xdef857ac },
  { 'dupe': true, 'type': 8, 'name': 'style.css', 'dir': 'c4', 'linked': 2, 'url': 'http://107.20.213.223/style.css', 'fetched': true, 'code': 200, 'len': 8916, 'decl_mime': 'text/css', 'sniff_mime': 'text/css', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff6d5cd },
  { 'dupe': false, 'type': 32, 'name': 'artist.php', 'dir': 'c5', 'linked': 5, 'url': 'http://107.20.213.223/artist.php', 'fetched': false, 'error': 'Local network error', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 0, 3, 0, 0, 0 ], 'sig': 0x71bd297e },
  { 'dupe': false, 'type': 32, 'name': 'control.php', 'dir': 'c6', 'linked': 5, 'url': 'http://107.20.213.223/control.php', 'fetched': true, 'code': 404, 'len': 297, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'iso-8859-1', 'missing': true, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 0, 0, 0, 0, 1 ], 'sig': 0xd568acab },
  { 'dupe': false, 'type': 32, 'name': 'nslookup.php', 'dir': 'c7', 'linked': 2, 'url': 'http://107.20.213.223/nslookup.php', 'fetched': false, 'error': 'Local network error', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 1, 0, 0, 0 ], 'sig': 0x6a841831 },
  { 'dupe': true, 'type': 32, 'name': 'phpinfo.php', 'dir': 'c8', 'linked': 2, 'url': 'http://107.20.213.223/phpinfo.php', 'fetched': false, 'error': 'Local network error', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x6a841831 }
];
